---
- name: First step of prereq
  debug:
    msg: "This is a test"

- name: Make images directory
  ansible.builtin.file:
    path: "/var/lib/rancher/k3s/agent/images/"
    mode: 0755
    state: directory

- name: Distribute K3s amd64 images
  ansible.builtin.copy:
    src: "{{ airgap_dir }}/k3s-airgap-images-amd64.tar.gz"
    dest: /var/lib/rancher/k3s/agent/images/k3s-airgap-images-amd64.tar
    owner: root
    group: root
    mode: 0755

- name: Distribute K3s binary
  ansible.builtin.copy:
    src: "{{ airgap_dir }}/k3s"
    dest: /usr/local/bin/k3s
    owner: root
    group: root
    mode: 0755

# If airgapped, all K3s artifacts are already on the node.
- name: Download K3s install script
  ansible.builtin.get_url:
    url: https://get.k3s.io/
    timeout: 120
    dest: /usr/local/bin/k3s-install.sh
    owner: root
    group: root
    mode: 0755

# - name: Download K3s binary
#   ansible.builtin.command:
#     cmd: /usr/local/bin/k3s-install.sh
#   environment:
#     INSTALL_K3S_SKIP_START: "true"
#     INSTALL_K3S_VERSION: "{{ k3s_version }}"
#   changed_when: true

