---
- name: First step of prereq
  debug:
    msg: "This is a test"

# - name: Enable IPv4 forwarding
#   ansible.posix.sysctl:
#     name: net.ipv4.ip_forward
#     value: "1"
#     state: present
#     reload: true
